Algoritmo "divisivel_por_4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exercicio F página 66 Manzano
// Autor(a)    : Fellype
// Data atual  : 21/04/2024
Var
// Seção de Declarações das variáveis
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   Para numero de 1 ate 200 Passo 1 Faça
      Se numero % 4 = 0 Então
         escreval(numero)
      FimSe
   FimPara

Fimalgoritmo