Algoritmo "soma100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exercicio C da página 66
// Autor(a)    : Fellype
// Data atual  : 21/04/2024
Var
   // Seção de Declarações das variáveis
   numero, soma: inteiro

Inicio
   Para numero de 1 ate 100 Faça
      soma <- soma + numero
   FimPara

   Escreval("A soma dos 100 primeiros números é ", soma)
Fimalgoritmo