Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exercicio B da página 66
// Autor(a)    : Fellype
// Data atual  : 21/04/2024
Var
   // Seção de Declarações das variáveis
   numero, contadora: inteiro

Inicio

Escreva("Digite um número que te darei sua tabuada: ")
leia(numero)

   Para contadora de 1 ate 10 Faça
      Escreval(numero, " X ", contadora, " = ", numero * contadora)
   FimPara
Fimalgoritmo