Algoritmo "Impar_ou_par"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson 
// Descrição   : Exercicio 4)J Manzano
// Autor(a)    : Fellype
// Data atual  : 21/04/2024
Var
// Seção de Declarações das variáveis 
valorA: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número: ")
leia(valorA)

limpatela

se (valorA % 2 = 0)  entao
   escreva("O número é Par.")

senao
     escreva("O número é Impar.")
fimse

Fimalgoritmo