Algoritmo "Enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson 
// Descrição   : Estrutura de repetição
// Autor(a)    : Fellype
// Data atual  : 27/03/2024
Var
// Seção de Declarações das variáveis 
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora < 10 faça
         Escreval("Fellype")
         contadora <- contadora + 1
fimenquanto
Fimalgoritmo