Algoritmo "divisivelpor4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exercicio C da página 50
// Autor(a)    : Fellype
// Data atual  : 21/04/2024
Var
   // Seção de Declarações das variáveis
numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   numero <- 1
   repita
      se numero % 2 = 0 entao
         escreva(numero)
      fimse
      numero <- numero + 1
   ate numero >= 200


Fimalgoritmo