Algoritmo "repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson 
// Descrição   : Estrutura de repetição Repita
// Autor(a)    : Fellype
// Data atual  : 03/04/2024
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
      escreval("Aqui sou eu")
      num <- num + 1
      ate num > 9



Fimalgoritmo